# Rate-limiting queries.

[listeners.local-udp]
address = "127.0.0.1:53"
protocol = "udp"
resolver = "cloudflare-logged"

[groups.cloudflare-logged]
type = "syslog"
resolvers = ["cloudflare-dot"]
network = "udp" # "udp", "tcp", "unix"
address = "192.168.0.1:514" # Defaults to the local syslog server
priority = "info" # "emergency", "alert", "critical", "error", "warning", "notice", "info", "debug"
tag = "routedns"
log-request = true
log-response = true
verbose = true # Log all answers, not just the type that match the query

[resolvers.cloudflare-dot]
address = "1.1.1.1:853"
protocol = "dot"

