on:
  release:
    types: [published]

jobs:
  release-android-arm:
    name: release android/arm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Compile and upload release
      uses: StevenCyb/sc-go-cross-build@0.1.0
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
        platform: "android/arm"

  release-android-arm64:
    name: release android/arm64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Compile and upload release
      uses: StevenCyb/sc-go-cross-build@0.1.0
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
        platform: "android/arm64"

  release-linux-386:
    name: release linux/386
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Compile and upload release
      uses: StevenCyb/sc-go-cross-build@0.1.0
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
        platform: "linux/386"

  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Compile and upload release
      uses: StevenCyb/sc-go-cross-build@0.1.0
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
        platform: "linux/amd64"

  release-windows-386:
    name: release windows/386
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Compile and upload release
      uses: StevenCyb/sc-go-cross-build@0.1.0
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
        platform: "windows/386"

  release-windows-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Compile and upload release
      uses: StevenCyb/sc-go-cross-build@0.1.0
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
        platform: "windows/amd64"
